import { useMemo, useState } from 'react';
import { documents, fileTypes, metadataChoices } from './data/mockData';
import { DocumentFilters } from './components/DocumentFilters';
import { DocumentTable } from './components/DocumentTable';
import { Header } from './components/Header';
import { Insights } from './components/Insights';
import { MetadataExplorer } from './components/MetadataExplorer';
import { Metrics } from './components/Metrics';
import { ViewTabs } from './components/ViewTabs';
import type { Filters, MetadataChoice } from './types/documents';
import styles from './styles.module.css';

const initialFilters: Filters = { domain: 'All', choice: null, fileType: 'All', status: 'All', sensitivity: 'All', query: '', choiceQuery: '', classification: 'Combined' };
export default function App() { const [filters, setFilters] = useState<Filters>(initialFilters); const update = <Key extends keyof Filters>(key: Key, value: Filters[Key]) => setFilters(current => ({ ...current, [key]: value })); const filteredDocuments = useMemo(() => documents.filter(doc => (filters.classification === 'Combined' || doc.classification === filters.classification) && (!filters.choice || doc.choice.id === filters.choice.id) && (filters.fileType === 'All' || doc.type === filters.fileType) && (filters.status === 'All' || doc.status === filters.status) && (filters.sensitivity === 'All' || doc.sensitivity === filters.sensitivity) && (!filters.query || [doc.title, doc.id, doc.author, doc.choice.name].join(' ').toLowerCase().includes(filters.query.toLowerCase()))), [filters]); const visibleChoices = useMemo(() => metadataChoices.filter(choice => (filters.domain === 'All' || choice.domain === filters.domain) && `${choice.id} ${choice.name}`.toLowerCase().includes(filters.choiceQuery.toLowerCase())), [filters.domain, filters.choiceQuery]); const topChoices = useMemo(() => [...metadataChoices].sort((a, b) => b.count - a.count).slice(0, 7), []); const typeCounts = useMemo(() => fileTypes.map(type => ({ type, count: filteredDocuments.filter(doc => doc.type === type).length })), [filteredDocuments]); const activeTotal = documents.filter(doc => filters.classification === 'Combined' || doc.classification === filters.classification).length; const setChoice = (choice: MetadataChoice | null) => update('choice', choice); return <div className={styles.appShell}><Header onReset={() => setFilters(initialFilters)} /><main className={styles.main}><ViewTabs value={filters.classification} onChange={value => update('classification', value)} /><Metrics total={activeTotal} choices={new Set(filteredDocuments.map(doc => doc.choice.id)).size} protectedDocuments={filteredDocuments.filter(doc => doc.sensitivity === 'Restricted' || doc.sensitivity === 'Confidential').length} /><MetadataExplorer choices={visibleChoices} activeDomain={filters.domain} selectedChoice={filters.choice} query={filters.choiceQuery} onDomainChange={value => update('domain', value)} onQueryChange={value => update('choiceQuery', value)} onChoiceChange={setChoice} /><Insights topChoices={topChoices} counts={typeCounts} total={filteredDocuments.length} /><DocumentFilters choice={filters.choice} fileType={filters.fileType} status={filters.status} sensitivity={filters.sensitivity} query={filters.query} onChoiceChange={setChoice} onFileTypeChange={value => update('fileType', value)} onStatusChange={value => update('status', value)} onSensitivityChange={value => update('sensitivity', value)} onQueryChange={value => update('query', value)} /><DocumentTable documents={filteredDocuments} selectedChoice={filters.choice} onChoiceChange={setChoice} /></main></div>; }
